### PR TITLE
Process graphviz diagrams.

### PR DESCRIPTION
**Pull request by jonathanpallant**
Replaces mermaid support (which doesn't work well with reveal.js and RevealMarkdown).

I prefer this over #23 and #22. But you have to re-write your diagrams as Graphviz dot syntax.

### CODE REVIEW

**Comment by jonathanpallant** [comment]
I think we can publish this because anything other than `dot process` blocks are left exactly as before.

**Review by Hoverbear — APPROVED** [review]
Can't give a very comprehensive review here but everything appears as I'd expect and the checks pass.

**Comment by jonathanpallant** [comment]
Actually, I should add a test containing a dot diagram.

**Comment by tshepang** [comment]
running `cargo test` fails locally for me...
> test build_slides ... FAILED

**Comment by jonathanpallant** [comment]
What does:

```
$ diff -r ./tests/reference_out ./tests/data_out
```

say? Do you have Graphviz installed?

**Comment by tshepang** [comment]
```diff
❯ diff -r ./tests/reference_out ./tests/data_out
diff --color=auto -r ./tests/reference_out/chapter_2.html ./tests/data_out/chapter_2.html
13c13
< <!-- Generated by graphviz version 2.43.0 (0)
---
> <!-- Generated by graphviz version 12.2.0 (20241103.1931)
15c15
< <!-- Title: %3 Pages: 1 -->
---
> <!-- Pages: 1 -->
19,20c19
< <title>%3</title>
< <polygon fill="white" stroke="transparent" points="-4,4 -4,-41 58,-41 58,4 -4,4"/>
---
> <polygon fill="white" stroke="none" points="-4,4 -4,-41 58,-41 58,4 -4,4"/>
25c24
< <text text-anchor="middle" x="27" y="-14.8" font-family="Times,serif" font-size="14.00">X</text>
---
> <text text-anchor="middle" x="26.88" y="-13.45" font-family="Times,serif" font-size="14.00">X</text>
```
yeah, it's installed... version 12.2.0

**Comment by jonathanpallant** [comment]
That diff seems fine. I see the same.

**Pull request merged**
